version: '3'

services:
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mysql+mysqlconnector://test_username:test_password@db:3306/test_database
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test_password_root
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_username
      MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
